### ISSUE TITLE
Enable Suggestions on Multiple Lines for Smaller Screens

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-geocoder#264]
I have an idea for a user improvement for suggestions on smaller screens.  I'm not sure if a code change, or content on the documentation site is the best place for this.  The basic idea is that on smaller screens, suggestions would appear on multiple lines, instead of disappear off-screen (the default behavior).  

Below is sample code and a screen-shot.  I don't think this should be enabled by default, but I think an option to enable this, or at least show a code sample would benefit users.

```css
/* have suggestions break onto multiple lines */
  .geocoder-control-suggestion {
    overflow-wrap: break-word !important;
    word-break: break-all !important;
    overflow: visible !important;
    white-space: break-spaces !important;
}
```

![Screenshot_20210111-150521](https://user-images.githubusercontent.com/12861454/104232785-d0935280-541e-11eb-8343-bbb83e5f4d76.png)
